version: '3.8'

services:
  npm.pihole.sync:
    build: .
    container_name: npm.pihole.sync
    environment:
      PIHOLE_IP: 192.168.1.100
      NPM_SERVER_IP: 192.168.1.101
      PIHOLE_USER: admin
      PIHOLE_PASS: password
    volumes:
      - /path/to/proxy_host:/data/nginx/proxy_host
