version: '3.8'

services:
  npm.pihole.sync:
    image: ghcr.io/fjbravo/npm.pihole.sync:latest
    container_name: npm.pihole.sync
    environment:
      PIHOLE_IP: 192.168.1.100
      NPM_SERVER_IP: 192.168.1.101
      PIHOLE_USER: admin
      PIHOLE_PASS: password
      DRY_RUN: true
    volumes:
      - /data/nginx/proxy_host:/data/nginx/proxy_host
